schema:
    dir: '/home/ubuntu/RADAR-Schemas/commons'
    key_cols: ['projectId', 'userId', 'sourceId']
    read_csvs: True


specifications:
    dir: '/home/ubuntu/RADAR-Schemas/specifications'

protocol:
    url: 'https://raw.githubusercontent.com/RADAR-base/RADAR-aRMT-protocols/master/RADAR-MDD-KCL-s1/protocol.json'
